### ISSUE TITLE
Add "Button Label" to README

### ISSUE THREAD

**Issue by frunika** [tobimori/streamdeck-toggl#11]
I really love your implementation! It's very useful, even if it just installed it :)

I'm not quite shure what the "Button Label" does. The README doesn't contain any information about it.

**Comment by tobimori** [comment]
Button Label allows you to set a label on the button and has the same functionality as the default title option, although it allows me to programmatically set the title to the current entries' duration. I'll update this with the rewrite I'm currently working on.
