### ISSUE TITLE
Show Tracking Time

### ISSUE THREAD

**Issue by frunika** [tobimori/streamdeck-toggl#14]
Don't know if the toggl API supports it, but showing the current tracking time on the deck would be awesome :)

**Comment by rallman** [comment]
If you leave the `Title` field empty and use `Button Label` instead, the time will be displayed. This seems to be an issue with the `setTitle` action in Strem Deck.

https://www.reddit.com/r/StreamDeckSDK/comments/axp0zp/how_to_update_title_field_in_property_inspector/
