### ISSUE TITLE
Use setGlobalSettings to store token while allowing multiple accounts

### ISSUE THREAD

**Issue by pedropombeiro** [tobimori/streamdeck-toggl#24]
It would be nice to use [setGlobalSettings](https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#setglobalsettings) to store the token, so that we wouldn't need to copy the token to each button (in my case I have 8 button instances).

**Comment by tobimori** [comment]
This was disabled due to people wanting to use multiple account. The rewrite I'm currently working on will feature multi-accounting with global settings.
