### ISSUE TITLE
Custom Button Missing Task option

### ISSUE THREAD

**Issue by WDrake98** [tobimori/streamdeck-toggl#32]
The current configuration doesn't include a text box to enter a task, nor does the project dropdown include tasks under a project.  

![image](https://user-images.githubusercontent.com/5875789/151919589-c0f9ce63-fdfa-40e4-b212-c0eca1d7d353.png)

https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#time-entries
tid: task ID (integer, not required)

Get project tasks: https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md#get-project-tasks
GET https://api.track.toggl.com/api/v8/projects/{project_id}/task

**Comment by tobimori** [comment]
See #25
