### ISSUE TITLE
Updated Release for APIv8 Depreciation 

### ISSUE THREAD

**Issue by angry-bender** [tobimori/streamdeck-toggl#41]
I noticed @matejcerny was able to upgrade the API to v9 2 days ago.

Just wondering if @tobimori can look to release an updated compiled version for the Elgato store before the upcoming V8 API depreciation on May16? As per PR #40 or if we should look to compile locally?

**Comment by matejcerny** [comment]
Unfortunately the contract which @tobimori used for pushing updates left Elgato, so we need to find another way. Do you have any experience with the Elgato store?

**Comment by malde** [comment]
Has that been tested? I couldn't get your version to work locally.
I did however find another fork that already did some v9 conversion, which does work (but has some issues with displaying the time, and could use some polishing): https://github.com/Barndtt/streamdeck-toggl

**Comment by jpcartailler** [comment]
Regarding the Elgato store - there is some information at https://docs.elgato.com/sdk/plugins/distribution. 

Submit your plugins by sending an email to [maker@elgato.com](mailto:maker@elgato.com?subject=New%20Plugin:%20&body=Hello%20Elgato%20Team,%0D%0A%0D%0AUser:%0D%0A%0D%0ARelease%20Notes:%0D%0A%0D%0ASupport%20Link:%0D%0A%0D%0ACategory:) with the following:

    Download: A link to download the plugin.

    User: A unique username or an email address.

    Release Notes: What changed with the new version of your plugin? (features/bug fixes)

    Support: Where can users contact you if they have problems? (email, contact form, etc.)

    Category: Under which category do you want to have your plugin listed in the store (only one category is allowed at the moment).

**Comment by angry-bender** [comment]
> Unfortunately the contact which @tobimori used for pushing updates left Elgato, so we need to find another way. Do you have any experience with the Elgato store?

Me personally, no, I havent even compiled a plugin locally unfortunately, was more looking to scope out the requirements before May to see what I need to learn, or if we could get an updated release 🫠

**Comment by tobimori** [comment]
"back then" compilation was just making a zip file with the elgato cli, not sure if that has changed much.

**Comment by matejcerny** [comment]
Sorry guys, as the change was not that big, I only tested it in postman. @malde You are right, I will try to fix it as soon as possible.

**Comment by matejcerny** [comment]
This one has been tested and it works. Sadly, the issue with displaying the time persists. Can anyone investigate it 🙏? https://github.com/tobimori/streamdeck-toggl/pull/42

**Comment by angry-bender** [comment]
Just by downloading your zip, and replacing the contents in the `%appdata%\elgato\StreamDeck\Plugins\io.moeritz.streamdeck.toggl.sdplugin` it appears to work for time tracking.

I don't see the time issues on the deck, but I don't usually use that feature, rather I just use it to quickly switch projects.

Similar to other repos listed in this issue, might be good to update the readme with the instructions so people don't think they need to recompile 😊

Thank you

**Comment by matejcerny** [comment]
This is how it looks like.
 
<img width="96" alt="image" src="https://github.com/tobimori/streamdeck-toggl/assets/35267431/df4c2e1f-c53f-4d53-b967-44e64cacaf1c">

**Comment by malde** [comment]
Now that I see the full number (I didn't because font-size), I'm pretty sure that's just a local datetime conversion issue on the deck. Those 476,238 hours at least match the hours since 1.1.1970.

**Comment by matejcerny** [comment]
Well, it looks like API does not send a duration anymore:

```json
{
    ...
    "task_id": null,
    "billable": false,
    "start": "2024-04-30T06:43:55+00:00",
    "stop": null,
    "duration": -1,
    "description": "work",
    "tags": [],
    "tag_ids": [],
    "duronly": true,
    "at": "2024-04-30T06:43:56+00:00",
    "server_deleted_at": null,
    "user_id": 9275401,
    ...
    "permissions": null
}
```

**Comment by matejcerny** [comment]
Works on my machine. @malde Can you please also test it? Thanks a lot! https://github.com/tobimori/streamdeck-toggl/pull/43

**Comment by malde** [comment]
Looks to be working for me 👍

**Comment by angry-bender** [comment]
> This is how it looks like.
>  
> <img width="96" alt="image" src="https://github.com/tobimori/streamdeck-toggl/assets/35267431/df4c2e1f-c53f-4d53-b967-44e64cacaf1c">
> 

Ahh I removed that text In the UI for my use case 😊

**Comment by matejcerny** [comment]
Do you have the latest version @angry-bender? https://github.com/tobimori/streamdeck-toggl/pull/43

**Comment by angry-bender** [comment]
Looks to be right for me 
![image](https://github.com/tobimori/streamdeck-toggl/assets/18164137/5638c453-98e4-422a-b898-1050dcce6af3)

**Comment by matejcerny** [comment]
Hopefully the last change: (https://github.com/tobimori/streamdeck-toggl/pull/45)

**Comment by matejcerny** [comment]
> Regarding the Elgato store - there is some information at https://docs.elgato.com/sdk/plugins/distribution.
> 
> Submit your plugins by sending an email to [maker@elgato.com](mailto:maker@elgato.com?subject=New%20Plugin:%20&body=Hello%20Elgato%20Team,%0D%0A%0D%0AUser:%0D%0A%0D%0ARelease%20Notes:%0D%0A%0D%0ASupport%20Link:%0D%0A%0D%0ACategory:) with the following:
> 
> ```
> Download: A link to download the plugin.
> 
> User: A unique username or an email address.
> 
> Release Notes: What changed with the new version of your plugin? (features/bug fixes)
> 
> Support: Where can users contact you if they have problems? (email, contact form, etc.)
> 
> Category: Under which category do you want to have your plugin listed in the store (only one category is allowed at the moment).
> ```


@tobimori Can you please send it as an author? This is the bundle, just delete the `.md` extension (I was unable to upload it here without it)

[io.moeritz.streamdeck.toggl.streamDeckPlugin.md](https://github.com/tobimori/streamdeck-toggl/files/15272924/io.moeritz.streamdeck.toggl.streamDeckPlugin.md)

**Comment by angry-bender** [comment]
> > Regarding the Elgato store - there is some information at https://docs.elgato.com/sdk/plugins/distribution.
> > 
> > Submit your plugins by sending an email to [maker@elgato.com](mailto:maker@elgato.com?subject=New%20Plugin:%20&body=Hello%20Elgato%20Team,%0D%0A%0D%0AUser:%0D%0A%0D%0ARelease%20Notes:%0D%0A%0D%0ASupport%20Link:%0D%0A%0D%0ACategory:) with the following:
> > 
> > ```
> > Download: A link to download the plugin.
> > 
> > User: A unique username or an email address.
> > 
> > Release Notes: What changed with the new version of your plugin? (features/bug fixes)
> > 
> > Support: Where can users contact you if they have problems? (email, contact form, etc.)
> > 
> > Category: Under which category do you want to have your plugin listed in the store (only one category is allowed at the moment).
> > ```
> 
> 
> @tobimori Can you please send it as an author? This is the bundle, just delete the `.md` extension (I was unable to upload it here without it)
> 
> [io.moeritz.streamdeck.toggl.streamDeckPlugin.md](https://github.com/tobimori/streamdeck-toggl/files/15272924/io.moeritz.streamdeck.toggl.streamDeckPlugin.md)
> 
> 
> 
> 

Looks like it's published https://marketplace.elgato.com/product/toggl-b040b224-5e61-4722-957f-91a662792441

**Comment by tobimori** [comment]
thanks all for your efforts with this and sorry I wasn't able to provide more assistance than this :)
