### ISSUE TITLE
Broken behaviour with buttons with empty entry names

### ISSUE THREAD

**Issue by tobimori** [tobimori/streamdeck-toggl#5]

**Comment by anthonybaldwin** [comment]
I have to have all three of these fields populated for the Toggl button to work as expected:

- Button Label
- Entry Name
- Project

**Comment by tobimori** [comment]
Thats right. I opened this issue to work on a fix for the need to fill up the Entry Name :)

**Comment by anthonybaldwin** [comment]
Sorry, main point was that Project is also required on top of Entry Name. I was wrong about Button Label it looks like...not sure that is TBH.

Appreciate your work! :)

**Comment by tobimori** [comment]
Ah, Project shouldn't be required either. Only the workspace. Will look that up.
Button Label ist just because when you set a name for the button the time won't be shown, that's just cosmetical.

**Comment by tobimori** [comment]
Fixing this in the rewrite.
