### ISSUE TITLE
Toggle option to start/stop toggl timer

### ISSUE THREAD

**Issue by milindian** [tobimori/streamdeck-toggl#8]
Instead of the action always starting a new timer, it would be nice if you could start/stop

**Comment by tobimori** [comment]
Hi,

if all entry options are the same, pressing a button will stop the running entry.
This isn't working with an Empty Entry Name right now.

**Comment by IsaacYongTY** [comment]
I've tested it and the start/stop can be toggled only when there is both Entry Name and Project selected

**Comment by jawn** [comment]
> This isn't working with an Empty Entry Name right now.

Is that a bug (seems like it) ?

**Comment by pedropombeiro** [comment]
It would be nice if it could Continue/Pause (that's the only reason I haven't been using this plugin and use a Multi Action Switch instead - with the inconvenience that it doesn't sync to the actual timer state).

**Comment by tobimori** [comment]
Will be added as new action in the 2.0 Typescript rewrite I'm working on rn.
